# Generated by Django 6.0 on 2026-04-24 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_no', models.CharField(max_length=64)),
                ('template_name', models.CharField(max_length=200)),
                ('template_desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('question_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'survey_template',
                'verbose_name_plural': 'survey_template',
                'db_table': 'survey_template',
                'constraints': [models.UniqueConstraint(fields=('template_no',), name='uk_survey_template_template_no')],
            },
        ),
        migrations.CreateModel(
            name='SurveyTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('survey_no', models.CharField(max_length=64)),
                ('survey_title', models.CharField(blank=True, max_length=200, null=True)),
                ('survey_desc', models.TextField(blank=True, null=True)),
                ('survey_status', models.CharField(max_length=32)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('allow_submit', models.SmallIntegerField(default=1)),
                ('question_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tickets.ticket')),
                ('template', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='surveys.surveytemplate')),
            ],
            options={
                'verbose_name': 'survey_task',
                'verbose_name_plural': 'survey_task',
                'db_table': 'survey_task',
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplateQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_no', models.IntegerField(default=0)),
                ('question_no', models.CharField(max_length=64)),
                ('question_title', models.CharField(max_length=200)),
                ('question_type', models.CharField(max_length=32)),
                ('is_required', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='surveys.surveytemplate')),
            ],
            options={
                'verbose_name': 'survey_template_question',
                'verbose_name_plural': 'survey_template_question',
                'db_table': 'survey_template_question',
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplateOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_no', models.IntegerField(default=0)),
                ('option_no', models.CharField(max_length=64)),
                ('option_text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='surveys.surveytemplatequestion')),
            ],
            options={
                'verbose_name': 'survey_template_option',
                'verbose_name_plural': 'survey_template_option',
                'db_table': 'survey_template_option',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_no', models.CharField(max_length=64)),
                ('question_title', models.CharField(max_length=200)),
                ('question_type', models.CharField(max_length=32)),
                ('answer_option_no', models.CharField(blank=True, max_length=64, null=True)),
                ('answer_option_text', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey_task', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='surveys.surveytask')),
                ('question', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='surveys.surveytemplatequestion')),
            ],
            options={
                'verbose_name': 'survey_answer',
                'verbose_name_plural': 'survey_answer',
                'db_table': 'survey_answer',
            },
        ),
        migrations.AddIndex(
            model_name='surveytask',
            index=models.Index(fields=['ticket', 'survey_status'], name='idx_survey_task_ticket_status'),
        ),
        migrations.AddConstraint(
            model_name='surveytask',
            constraint=models.UniqueConstraint(fields=('survey_no',), name='uk_survey_task_survey_no'),
        ),
        migrations.AddIndex(
            model_name='surveytemplatequestion',
            index=models.Index(fields=['template', 'sort_no'], name='idx_survey_template_question_template_sort'),
        ),
        migrations.AddConstraint(
            model_name='surveytemplatequestion',
            constraint=models.UniqueConstraint(fields=('template', 'question_no'), name='uk_survey_template_question_template_question_no'),
        ),
        migrations.AddIndex(
            model_name='surveytemplateoption',
            index=models.Index(fields=['question', 'sort_no'], name='idx_survey_template_option_question_sort'),
        ),
        migrations.AddConstraint(
            model_name='surveytemplateoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_no'), name='uk_survey_template_option_question_option_no'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['survey_task'], name='idx_survey_answer_task_id'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['question'], name='idx_survey_answer_question_id'),
        ),
    ]
