# Generated by Django 6.0 on 2026-04-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WfAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biz_type', models.CharField(max_length=32)),
                ('action_code', models.CharField(max_length=64)),
                ('action_name', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=32)),
                ('need_remark', models.SmallIntegerField(default=0)),
                ('need_attachment', models.SmallIntegerField(default=0)),
                ('need_confirm', models.SmallIntegerField(default=0)),
                ('need_operator', models.SmallIntegerField(default=1)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'wf_action',
                'verbose_name_plural': 'wf_action',
                'db_table': 'wf_action',
                'constraints': [models.UniqueConstraint(fields=('biz_type', 'action_code'), name='uk_wf_action_biz_type_action_code')],
            },
        ),
        migrations.CreateModel(
            name='WfActionPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biz_type', models.CharField(max_length=32)),
                ('status_code', models.CharField(max_length=64)),
                ('action_code', models.CharField(max_length=64)),
                ('role_code', models.CharField(max_length=64)),
                ('allow_execute', models.SmallIntegerField(default=1)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'wf_action_permission',
                'verbose_name_plural': 'wf_action_permission',
                'db_table': 'wf_action_permission',
                'constraints': [models.UniqueConstraint(fields=('biz_type', 'status_code', 'action_code', 'role_code'), name='uk_wf_action_permission_core')],
            },
        ),
        migrations.CreateModel(
            name='WfAutoRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biz_type', models.CharField(max_length=32)),
                ('rule_code', models.CharField(max_length=64)),
                ('from_status_code', models.CharField(max_length=64)),
                ('action_code', models.CharField(max_length=64)),
                ('trigger_mode', models.CharField(max_length=32)),
                ('trigger_expr', models.TextField(blank=True, null=True)),
                ('calendar_type', models.CharField(blank=True, max_length=32, null=True)),
                ('is_holiday_excluded', models.SmallIntegerField(default=0)),
                ('retryable', models.SmallIntegerField(default=1)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'wf_auto_rule',
                'verbose_name_plural': 'wf_auto_rule',
                'db_table': 'wf_auto_rule',
                'indexes': [models.Index(fields=['biz_type', 'from_status_code', 'trigger_mode'], name='idx_wf_auto_rule_from_status_mode')],
                'constraints': [models.UniqueConstraint(fields=('biz_type', 'rule_code'), name='uk_wf_auto_rule_biz_type_rule_code')],
            },
        ),
        migrations.CreateModel(
            name='WfStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biz_type', models.CharField(max_length=32)),
                ('status_code', models.CharField(max_length=64)),
                ('status_name', models.CharField(max_length=100)),
                ('status_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('status_name_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('status_level', models.CharField(max_length=32)),
                ('main_status_code', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_status_code', models.CharField(blank=True, max_length=64, null=True)),
                ('progress_node_code', models.CharField(blank=True, max_length=64, null=True)),
                ('is_initial', models.SmallIntegerField(default=0)),
                ('is_final', models.SmallIntegerField(default=0)),
                ('is_system_only', models.SmallIntegerField(default=0)),
                ('allow_manual_set', models.SmallIntegerField(default=0)),
                ('sort_no', models.IntegerField(default=0)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'wf_status',
                'verbose_name_plural': 'wf_status',
                'db_table': 'wf_status',
                'indexes': [models.Index(fields=['biz_type', 'status_level', 'sort_no'], name='idx_wf_status_level_sort')],
                'constraints': [models.UniqueConstraint(fields=('biz_type', 'status_code'), name='uk_wf_status_biz_type_status_code')],
            },
        ),
        migrations.CreateModel(
            name='WfTransition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biz_type', models.CharField(max_length=32)),
                ('from_status_code', models.CharField(max_length=64)),
                ('action_code', models.CharField(max_length=64)),
                ('to_status_code', models.CharField(max_length=64)),
                ('transition_type', models.CharField(max_length=32)),
                ('role_code', models.CharField(blank=True, max_length=64, null=True)),
                ('is_system_only', models.SmallIntegerField(default=0)),
                ('condition_expr', models.TextField(blank=True, null=True)),
                ('condition_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'wf_transition',
                'verbose_name_plural': 'wf_transition',
                'db_table': 'wf_transition',
                'indexes': [models.Index(fields=['biz_type', 'from_status_code', 'action_code', 'priority'], name='idx_wf_transition_from_action_priority')],
                'constraints': [models.UniqueConstraint(fields=('biz_type', 'from_status_code', 'action_code', 'to_status_code'), name='uk_wf_transition_core')],
            },
        ),
    ]
