# Generated by Django 6.0 on 2026-04-24 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(max_length=32)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('default_address', models.CharField(blank=True, max_length=255, null=True)),
                ('marketing_agree', models.SmallIntegerField(default=0)),
                ('privacy_agree', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customer',
                'db_table': 'customer',
                'constraints': [models.UniqueConstraint(fields=('customer_phone',), name='uk_customer_phone')],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_code', models.CharField(max_length=64)),
                ('part_name', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_location', models.CharField(blank=True, max_length=100, null=True)),
                ('default_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'part',
                'verbose_name_plural': 'part',
                'db_table': 'part',
                'constraints': [models.UniqueConstraint(fields=('part_code',), name='uk_part_code')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(blank=True, max_length=64, null=True)),
                ('market_date', models.DateField(blank=True, null=True)),
                ('part_keep_until', models.DateField(blank=True, null=True)),
                ('stock_location', models.CharField(blank=True, max_length=100, null=True)),
                ('part_stock_location', models.CharField(blank=True, max_length=100, null=True)),
                ('safe_stock_threshold', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
                'db_table': 'product',
                'constraints': [models.UniqueConstraint(fields=('product_code',), name='uk_product_code')],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('store_code', models.CharField(max_length=64)),
                ('store_name', models.CharField(max_length=100)),
                ('store_type', models.CharField(blank=True, max_length=64, null=True)),
                ('store_address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'store',
                'db_table': 'store',
                'constraints': [models.UniqueConstraint(fields=('store_code',), name='uk_store_code')],
            },
        ),
        migrations.CreateModel(
            name='SysPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission_code', models.CharField(max_length=64)),
                ('permission_name', models.CharField(max_length=100)),
                ('permission_type', models.CharField(max_length=32)),
                ('permission_path', models.CharField(blank=True, max_length=255, null=True)),
                ('component_path', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_no', models.IntegerField(default=0)),
                ('is_visible', models.SmallIntegerField(default=1)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('permission_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.syspermission')),
            ],
            options={
                'verbose_name': 'sys_permission',
                'verbose_name_plural': 'sys_permission',
                'db_table': 'sys_permission',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=64)),
                ('role_name', models.CharField(max_length=100)),
                ('role_type', models.CharField(blank=True, max_length=64, null=True)),
                ('role_desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sys_role',
                'verbose_name_plural': 'sys_role',
                'db_table': 'sys_role',
                'constraints': [models.UniqueConstraint(fields=('role_code',), name='uk_sys_role_role_code')],
            },
        ),
        migrations.CreateModel(
            name='SysRolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_granted', models.SmallIntegerField(default=1)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.syspermission')),
                ('role', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.sysrole')),
            ],
            options={
                'verbose_name': 'sys_role_permission',
                'verbose_name_plural': 'sys_role_permission',
                'db_table': 'sys_role_permission',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_no', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('ip_match_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('allowed_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sys_user',
                'verbose_name_plural': 'sys_user',
                'db_table': 'sys_user',
                'constraints': [models.UniqueConstraint(fields=('user_no',), name='uk_sys_user_user_no')],
            },
        ),
        migrations.CreateModel(
            name='SysUserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.sysrole')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.sysuser')),
            ],
            options={
                'verbose_name': 'sys_user_role',
                'verbose_name_plural': 'sys_user_role',
                'db_table': 'sys_user_role',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warehouse_code', models.CharField(max_length=64)),
                ('warehouse_name', models.CharField(max_length=100)),
                ('warehouse_type', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'warehouse',
                'verbose_name_plural': 'warehouse',
                'db_table': 'warehouse',
                'constraints': [models.UniqueConstraint(fields=('warehouse_code',), name='uk_warehouse_code')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=64)),
                ('location_name', models.CharField(max_length=100)),
                ('location_type', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.warehouse')),
            ],
            options={
                'verbose_name': 'warehouse_location',
                'verbose_name_plural': 'warehouse_location',
                'db_table': 'warehouse_location',
            },
        ),
        migrations.CreateModel(
            name='PartConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty_type', models.CharField(max_length=64)),
                ('qty_name', models.CharField(max_length=100)),
                ('default_qty', models.IntegerField(default=0)),
                ('sort_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.part')),
            ],
            options={
                'verbose_name': 'part_config',
                'verbose_name_plural': 'part_config',
                'db_table': 'part_config',
                'indexes': [models.Index(fields=['part'], name='idx_part_config_part_id')],
            },
        ),
        migrations.AddIndex(
            model_name='syspermission',
            index=models.Index(fields=['parent'], name='idx_sys_permission_parent_id'),
        ),
        migrations.AddConstraint(
            model_name='syspermission',
            constraint=models.UniqueConstraint(fields=('permission_code',), name='uk_sys_permission_permission_code'),
        ),
        migrations.AddIndex(
            model_name='sysrolepermission',
            index=models.Index(fields=['permission'], name='idx_sys_role_permission_permission_id'),
        ),
        migrations.AddConstraint(
            model_name='sysrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uk_sys_role_permission_role_permission'),
        ),
        migrations.AddIndex(
            model_name='sysuserrole',
            index=models.Index(fields=['role'], name='idx_sys_user_role_role_id'),
        ),
        migrations.AddConstraint(
            model_name='sysuserrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uk_sys_user_role_user_role'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['warehouse'], name='idx_warehouse_location_warehouse_id'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'location_code'), name='uk_warehouse_location_warehouse_code'),
        ),
    ]
