# Generated by Django 6.0 on 2026-04-24 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInterfaceConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('system_code', models.CharField(max_length=64)),
                ('interface_type', models.CharField(max_length=64)),
                ('interface_name', models.CharField(blank=True, max_length=100, null=True)),
                ('endpoint_url', models.CharField(max_length=500)),
                ('http_method', models.CharField(blank=True, max_length=16, null=True)),
                ('sign_algorithm', models.CharField(blank=True, max_length=64, null=True)),
                ('sign_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('timeout_ms', models.IntegerField(default=5000)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'external_interface_config',
                'verbose_name_plural': 'external_interface_config',
                'db_table': 'external_interface_config',
                'constraints': [models.UniqueConstraint(fields=('system_code', 'interface_type'), name='uk_external_interface_config_system_type')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=64)),
                ('template_type', models.CharField(max_length=64)),
                ('template_name', models.CharField(max_length=200)),
                ('template_title', models.CharField(blank=True, max_length=200, null=True)),
                ('template_content', models.TextField(blank=True, null=True)),
                ('business_scene', models.CharField(blank=True, max_length=100, null=True)),
                ('trigger_node', models.CharField(blank=True, max_length=100, null=True)),
                ('lang_code', models.CharField(blank=True, max_length=20, null=True)),
                ('variable_desc', models.TextField(blank=True, null=True)),
                ('is_default', models.SmallIntegerField(default=0)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification_template',
                'verbose_name_plural': 'notification_template',
                'db_table': 'notification_template',
                'constraints': [models.UniqueConstraint(fields=('template_code',), name='uk_notification_template_template_code')],
            },
        ),
        migrations.CreateModel(
            name='NotificationSendLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('event_code', models.CharField(blank=True, max_length=64, null=True)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('channel_type', models.CharField(max_length=32)),
                ('template_name', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_type', models.CharField(blank=True, max_length=32, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_status', models.CharField(max_length=32)),
                ('retry_count', models.IntegerField(default=0)),
                ('fail_reason', models.TextField(blank=True, null=True)),
                ('callback_url', models.CharField(blank=True, max_length=500, null=True)),
                ('request_payload', models.TextField(blank=True, null=True)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.sysuser')),
                ('ticket', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tickets.ticket')),
                ('template', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'notification_send_log',
                'verbose_name_plural': 'notification_send_log',
                'db_table': 'notification_send_log',
                'indexes': [models.Index(fields=['ticket', 'sent_at'], name='idx_notification_send_log_ticket_sent_at'), models.Index(fields=['event_code', 'event_time'], name='idx_notification_send_log_event_code_time')],
                'constraints': [models.UniqueConstraint(fields=('message_id',), name='uk_notification_send_log_message_id')],
            },
        ),
        migrations.CreateModel(
            name='SysDictItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dict_type', models.CharField(max_length=64)),
                ('dict_code', models.CharField(max_length=64)),
                ('dict_name', models.CharField(max_length=100)),
                ('dict_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('dict_name_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_no', models.IntegerField(default=0)),
                ('is_default', models.SmallIntegerField(default=0)),
                ('status', models.CharField(default='ENABLED', max_length=32)),
                ('ext_value_1', models.CharField(blank=True, max_length=255, null=True)),
                ('ext_value_2', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notifications.sysdictitem')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.sysuser')),
            ],
            options={
                'verbose_name': 'sys_dict_item',
                'verbose_name_plural': 'sys_dict_item',
                'db_table': 'sys_dict_item',
                'indexes': [models.Index(fields=['dict_type', 'sort_no'], name='idx_sys_dict_item_type_sort'), models.Index(fields=['parent'], name='idx_sys_dict_item_parent_id')],
                'constraints': [models.UniqueConstraint(fields=('dict_code',), name='uk_sys_dict_item_dict_code')],
            },
        ),
    ]
