INSERT INTO sys_role_permission (
  role_id, permission_id, is_granted, remark, created_at, updated_at
) VALUES
((SELECT id FROM sys_role WHERE role_code = 'CS_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_TICKET'), 1, '客服主管可访问工单管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'CS_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_APPROVE'), 1, '客服主管可审核通过', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'CS_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_REJECT'), 1, '客服主管可审核驳回', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'CS_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_RECEIVE'), 1, '客服主管可确认接收', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'RECEIVE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_TICKET'), 1, '接收专员可访问工单管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'RECEIVE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_RECEIVE'), 1, '接收专员可确认接收', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'JUDGE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_TICKET'), 1, '判定专员可访问工单管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'JUDGE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_JUDGE_FREE'), 1, '判定专员可提交无偿判定', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'JUDGE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_JUDGE_PAID'), 1, '判定专员可提交有偿判定', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'JUDGE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_CREATE_PAYMENT'), 1, '判定专员可生成支付单', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SERVICE_ENGINEER'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_TICKET'), 1, '服务工程师可访问工单管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SERVICE_ENGINEER'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_MARK_WAIT_PARTS'), 1, '服务工程师可开始处理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SERVICE_ENGINEER'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_SUBMIT_REPAIR_DONE'), 1, '服务工程师可提交处理完成', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'FULFILLMENT_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_TICKET'), 1, '履约专员可访问工单管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'FULFILLMENT_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_SUBMIT_OUTBOUND'), 1, '履约专员可提交出库', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'STORE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_TICKET'), 1, '门店操作员可访问工单管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'STORE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_CONFIRM_STORE_RECEIVE'), 1, '门店操作员可确认门店收货', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'STORE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_TICKET_CONFIRM_CUSTOMER_PICKUP'), 1, '门店操作员可确认客户取件', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_TICKET'), 1, '系统管理员可访问工单管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_INVENTORY'), 1, '系统管理员可访问库存管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_SURVEY'), 1, '系统管理员可访问问卷管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_SETTING'), 1, '系统管理员可访问系统配置', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_CONSULTATION'), 1, '系统管理员可访问咨询管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_INVENTORY_REQUEST'), 1, '系统管理员可访问库存申请管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_PART_REQUEST'), 1, '系统管理员可访问小零件申请管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_PRODUCT'), 1, '系统管理员可访问产品管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_PART'), 1, '系统管理员可访问小零件管理', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'MENU_USER_PERMISSION'), 1, '系统管理员可访问用户权限', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_DICT_MAINTAIN'), 1, '系统管理员可维护字典', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_NOTIFICATION_TEMPLATE_MAINTAIN'), 1, '系统管理员可维护通知模板', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_ROLE_MAINTAIN'), 1, '系统管理员可维护角色', NOW(), NOW()),
((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BTN_PERMISSION_MAINTAIN'), 1, '系统管理员可维护权限', NOW(), NOW());
