INSERT INTO wf_status (
  biz_type, status_code, status_name, status_name_en, status_name_ko,
  status_level, main_status_code, customer_status_code, progress_node_code,
  is_initial, is_final, is_system_only, allow_manual_set, sort_no, status,
  created_at, updated_at
) VALUES
('TICKET', 'MAIN_APPLY', '受理', 'Apply', '접수', 'MAIN', NULL, NULL, NULL, 0, 0, 0, 0, 10, 'ENABLED', NOW(), NOW()),
('TICKET', 'MAIN_RECEIVE', '接收', 'Receive', '접수확인', 'MAIN', NULL, NULL, NULL, 0, 0, 0, 0, 20, 'ENABLED', NOW(), NOW()),
('TICKET', 'MAIN_JUDGE', '判定', 'Judge', '판정', 'MAIN', NULL, NULL, NULL, 0, 0, 0, 0, 30, 'ENABLED', NOW(), NOW()),
('TICKET', 'MAIN_PAYMENT', '支付', 'Payment', '결제', 'MAIN', NULL, NULL, NULL, 0, 0, 0, 0, 40, 'ENABLED', NOW(), NOW()),
('TICKET', 'MAIN_PROCESS', '处理', 'Process', '처리', 'MAIN', NULL, NULL, NULL, 0, 0, 0, 0, 50, 'ENABLED', NOW(), NOW()),
('TICKET', 'MAIN_FULFILLMENT', '履约', 'Fulfillment', '출고/배송', 'MAIN', NULL, NULL, NULL, 0, 0, 0, 0, 60, 'ENABLED', NOW(), NOW()),
('TICKET', 'MAIN_COMPLETED', '完成', 'Completed', '완료', 'MAIN', NULL, NULL, NULL, 0, 0, 0, 0, 70, 'ENABLED', NOW(), NOW()),
('TICKET', 'MAIN_CLOSED', '关闭', 'Closed', '종결', 'MAIN', NULL, NULL, NULL, 0, 0, 0, 0, 80, 'ENABLED', NOW(), NOW()),

('TICKET', 'CUSTOMER_APPLYING', '申请处理中', 'Applying', '신청 처리중', 'CUSTOMER', 'MAIN_APPLY', NULL, 'NODE_APPLY', 0, 0, 0, 0, 10, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_WAIT_RECEIVE', '待接收', 'Waiting Receive', '접수 대기', 'CUSTOMER', 'MAIN_RECEIVE', NULL, 'NODE_RECEIVE', 0, 0, 0, 0, 20, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_INSPECTING', '检测中', 'Inspecting', '검수중', 'CUSTOMER', 'MAIN_JUDGE', NULL, 'NODE_INSPECT', 0, 0, 0, 0, 30, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_WAIT_PAYMENT', '待支付', 'Waiting Payment', '결제 대기', 'CUSTOMER', 'MAIN_PAYMENT', NULL, 'NODE_PAYMENT', 0, 0, 0, 0, 40, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_PROCESSING', '处理中', 'Processing', '처리중', 'CUSTOMER', 'MAIN_PROCESS', NULL, 'NODE_PROCESS', 0, 0, 0, 0, 50, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_DELIVERING', '返还中', 'Delivering', '배송중', 'CUSTOMER', 'MAIN_FULFILLMENT', NULL, 'NODE_DELIVERY', 0, 0, 0, 0, 60, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_COMPLETED', '已完成', 'Completed', '완료', 'CUSTOMER', 'MAIN_COMPLETED', NULL, 'NODE_COMPLETED', 0, 1, 0, 0, 70, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_CLOSED', '已关闭', 'Closed', '종결', 'CUSTOMER', 'MAIN_CLOSED', NULL, 'NODE_CLOSED', 0, 1, 0, 0, 80, 'ENABLED', NOW(), NOW()),

('TICKET', 'WAIT_APPLY_REVIEW', '待申请审核', 'Wait Apply Review', '신청 검토 대기', 'BIZ', 'MAIN_APPLY', 'CUSTOMER_APPLYING', 'NODE_APPLY', 1, 0, 0, 0, 10, 'ENABLED', NOW(), NOW()),
('TICKET', 'APPLY_REJECTED', '申请审核驳回', 'Apply Rejected', '신청 반려', 'BIZ', 'MAIN_CLOSED', 'CUSTOMER_CLOSED', 'NODE_CLOSED', 0, 1, 0, 0, 20, 'ENABLED', NOW(), NOW()),
('TICKET', 'WAIT_RECEIVE', '待接收', 'Wait Receive', '접수 대기', 'BIZ', 'MAIN_RECEIVE', 'CUSTOMER_WAIT_RECEIVE', 'NODE_RECEIVE', 0, 0, 0, 0, 30, 'ENABLED', NOW(), NOW()),
('TICKET', 'RECEIVED', '已接收待检测', 'Received', '접수 완료', 'BIZ', 'MAIN_JUDGE', 'CUSTOMER_INSPECTING', 'NODE_RECEIVE', 0, 0, 0, 0, 40, 'ENABLED', NOW(), NOW()),
('TICKET', 'WAIT_JUDGE', '待判定', 'Wait Judge', '판정 대기', 'BIZ', 'MAIN_JUDGE', 'CUSTOMER_INSPECTING', 'NODE_INSPECT', 0, 0, 0, 0, 50, 'ENABLED', NOW(), NOW()),
('TICKET', 'JUDGED_COMPLETED', '服务判定完成', 'Judged Completed', '서비스 판정 완료', 'BIZ', 'MAIN_JUDGE', 'CUSTOMER_INSPECTING', 'NODE_INSPECT', 0, 0, 1, 0, 65, 'ENABLED', NOW(), NOW()),
('TICKET', 'JUDGED_FREE', '判定无偿', 'Judged Free', '무상 판정', 'BIZ', 'MAIN_PROCESS', 'CUSTOMER_PROCESSING', 'NODE_INSPECT', 0, 0, 1, 0, 70, 'ENABLED', NOW(), NOW()),
('TICKET', 'JUDGED_PAID', '判定有偿', 'Judged Paid', '유상 판정', 'BIZ', 'MAIN_PAYMENT', 'CUSTOMER_WAIT_PAYMENT', 'NODE_PAYMENT', 0, 0, 1, 0, 80, 'ENABLED', NOW(), NOW()),
('TICKET', 'WAIT_PAYMENT', '付款待机', 'Wait Payment', '결제 대기', 'BIZ', 'MAIN_PAYMENT', 'CUSTOMER_WAIT_PAYMENT', 'NODE_PAYMENT', 0, 0, 0, 0, 90, 'ENABLED', NOW(), NOW()),
('TICKET', 'PAYMENT_OVERDUE', '支付逾期', 'Payment Overdue', '결제 기한 초과', 'BIZ', 'MAIN_PAYMENT', 'CUSTOMER_WAIT_PAYMENT', 'NODE_PAYMENT', 0, 0, 1, 0, 95, 'ENABLED', NOW(), NOW()),
('TICKET', 'PAYMENT_COMPLETED', '支付完成', 'Payment Completed', '결제 완료', 'BIZ', 'MAIN_PROCESS', 'CUSTOMER_PROCESSING', 'NODE_PAYMENT', 0, 0, 1, 0, 100, 'ENABLED', NOW(), NOW()),
('TICKET', 'WAIT_REPAIR', '待处理', 'Wait Repair', '처리 대기', 'BIZ', 'MAIN_PROCESS', 'CUSTOMER_PROCESSING', 'NODE_PROCESS', 0, 0, 0, 0, 110, 'ENABLED', NOW(), NOW()),
('TICKET', 'REPAIRING', '处理中', 'Repairing', '처리중', 'BIZ', 'MAIN_PROCESS', 'CUSTOMER_PROCESSING', 'NODE_PROCESS', 0, 0, 0, 0, 120, 'ENABLED', NOW(), NOW()),
('TICKET', 'WAIT_PARTS', '等待配件', 'Wait Parts', '부품 대기', 'BIZ', 'MAIN_PROCESS', 'CUSTOMER_PROCESSING', 'NODE_PROCESS', 0, 0, 0, 0, 125, 'ENABLED', NOW(), NOW()),
('TICKET', 'WAIT_OUTBOUND', '待出库', 'Wait Outbound', '출고 대기', 'BIZ', 'MAIN_FULFILLMENT', 'CUSTOMER_PROCESSING', 'NODE_PROCESS', 0, 0, 0, 0, 130, 'ENABLED', NOW(), NOW()),
('TICKET', 'OUTBOUNDED', '已出库', 'Outbounded', '출고 완료', 'BIZ', 'MAIN_FULFILLMENT', 'CUSTOMER_DELIVERING', 'NODE_DELIVERY', 0, 0, 0, 0, 140, 'ENABLED', NOW(), NOW()),
('TICKET', 'DELIVERING', '配送中', 'Delivering', '배송중', 'BIZ', 'MAIN_FULFILLMENT', 'CUSTOMER_DELIVERING', 'NODE_DELIVERY', 0, 0, 0, 0, 150, 'ENABLED', NOW(), NOW()),
('TICKET', 'STORE_ARRIVED', '门店到货', 'Store Arrived', '매장 도착', 'BIZ', 'MAIN_FULFILLMENT', 'CUSTOMER_DELIVERING', 'NODE_DELIVERY', 0, 0, 0, 0, 160, 'ENABLED', NOW(), NOW()),
('TICKET', 'STORE_RECEIVED', '门店收货完成', 'Store Received', '매장 수령 완료', 'BIZ', 'MAIN_FULFILLMENT', 'CUSTOMER_DELIVERING', 'NODE_DELIVERY', 0, 0, 0, 0, 170, 'ENABLED', NOW(), NOW()),
('TICKET', 'STORE_READY_PICKUP', '门店可取', 'Store Ready Pickup', '매장 픽업 가능', 'BIZ', 'MAIN_FULFILLMENT', 'CUSTOMER_DELIVERING', 'NODE_DELIVERY', 0, 0, 0, 0, 175, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_SIGNED', '客户签收完成', 'Customer Signed', '고객 수령 완료', 'BIZ', 'MAIN_COMPLETED', 'CUSTOMER_COMPLETED', 'NODE_COMPLETED', 0, 0, 0, 0, 180, 'ENABLED', NOW(), NOW()),
('TICKET', 'CUSTOMER_PICKED', '客户取件完成', 'Customer Picked', '고객 픽업 완료', 'BIZ', 'MAIN_COMPLETED', 'CUSTOMER_COMPLETED', 'NODE_COMPLETED', 0, 0, 0, 0, 190, 'ENABLED', NOW(), NOW()),
('TICKET', 'COMPLETED', '服务完成', 'Completed', '서비스 완료', 'BIZ', 'MAIN_COMPLETED', 'CUSTOMER_COMPLETED', 'NODE_COMPLETED', 0, 1, 0, 0, 200, 'ENABLED', NOW(), NOW()),
('TICKET', 'REFUND_PROCESSING', '退款处理中', 'Refund Processing', '환불 처리중', 'BIZ', 'MAIN_CLOSED', 'CUSTOMER_CLOSED', 'NODE_CLOSED', 0, 0, 1, 0, 205, 'ENABLED', NOW(), NOW()),
('TICKET', 'REFUND_COMPLETED', '退款完成', 'Refund Completed', '환불 완료', 'BIZ', 'MAIN_CLOSED', 'CUSTOMER_CLOSED', 'NODE_CLOSED', 0, 1, 1, 0, 206, 'ENABLED', NOW(), NOW()),
('TICKET', 'CLOSED_UNPAID_RETURN', '未付款退回关闭', 'Closed Unpaid Return', '미결제 반송 종료', 'BIZ', 'MAIN_CLOSED', 'CUSTOMER_CLOSED', 'NODE_CLOSED', 0, 1, 0, 0, 210, 'ENABLED', NOW(), NOW()),
('TICKET', 'CLOSED_CANCELED', '取消关闭', 'Closed Canceled', '취소 종료', 'BIZ', 'MAIN_CLOSED', 'CUSTOMER_CLOSED', 'NODE_CLOSED', 0, 1, 0, 0, 220, 'ENABLED', NOW(), NOW()),

('PART_REQUEST', 'WAIT_OUTBOUND', '待出库', 'Wait Outbound', '출고 대기', 'BIZ', NULL, NULL, NULL, 1, 0, 0, 0, 10, 'ENABLED', NOW(), NOW()),
('PART_REQUEST', 'OUTBOUNDED', '已出库', 'Outbounded', '출고 완료', 'BIZ', NULL, NULL, NULL, 0, 0, 0, 0, 20, 'ENABLED', NOW(), NOW()),
('PART_REQUEST', 'COMPLETED', '已完成', 'Completed', '완료', 'BIZ', NULL, NULL, NULL, 0, 1, 0, 0, 30, 'ENABLED', NOW(), NOW()),
('PART_REQUEST', 'CLOSED', '已关闭', 'Closed', '종결', 'BIZ', NULL, NULL, NULL, 0, 1, 0, 0, 40, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'PENDING', '待处理', 'Pending', '대기', 'BIZ', NULL, NULL, NULL, 1, 0, 0, 0, 10, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'PROCESSING', '处理中', 'Processing', '처리중', 'BIZ', NULL, NULL, NULL, 0, 0, 0, 0, 20, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'WAIT_CONFIRM', '待客户确认', 'Wait Confirm', '고객 확인 대기', 'BIZ', NULL, NULL, NULL, 0, 0, 0, 0, 25, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'COMPLETED', '已完成', 'Completed', '완료', 'BIZ', NULL, NULL, NULL, 0, 1, 0, 0, 30, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'CLOSED', '已关闭', 'Closed', '종결', 'BIZ', NULL, NULL, NULL, 0, 1, 0, 0, 40, 'ENABLED', NOW(), NOW()),
('SURVEY', 'PENDING', '待填写', 'Pending', '대기', 'BIZ', NULL, NULL, NULL, 1, 0, 0, 0, 10, 'ENABLED', NOW(), NOW()),
('SURVEY', 'SUBMITTED', '已提交', 'Submitted', '제출 완료', 'BIZ', NULL, NULL, NULL, 0, 1, 0, 0, 20, 'ENABLED', NOW(), NOW()),
('SURVEY', 'EXPIRED', '已过期', 'Expired', '만료', 'BIZ', NULL, NULL, NULL, 0, 1, 1, 0, 30, 'ENABLED', NOW(), NOW()),
('SURVEY', 'INVALID', '已失效', 'Invalid', '무효', 'BIZ', NULL, NULL, NULL, 0, 1, 1, 0, 40, 'ENABLED', NOW(), NOW());
