INSERT INTO wf_action (
  biz_type, action_code, action_name, action_type,
  need_remark, need_attachment, need_confirm, need_operator,
  status, created_at, updated_at
) VALUES
('TICKET', 'APPLY_APPROVE', '申请审核通过', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'APPLY_REJECT', '申请审核驳回', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'CONFIRM_RECEIVE', '确认收到产品', 'MANUAL', 0, 0, 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'SUBMIT_JUDGE_FREE', '提交无偿判定', 'MANUAL', 1, 1, 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'SUBMIT_JUDGE_PAID', '提交有偿判定', 'MANUAL', 1, 1, 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'CREATE_PAYMENT_ORDER', '生成支付单', 'MANUAL', 0, 0, 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'PAY_SUCCESS', '支付成功回写', 'API', 0, 0, 0, 0, 'ENABLED', NOW(), NOW()),
('TICKET', 'MARK_PAYMENT_OVERDUE', '标记支付逾期', 'JOB', 0, 0, 0, 0, 'ENABLED', NOW(), NOW()),
('TICKET', 'PAY_TIMEOUT_CLOSE', '支付超时关闭', 'JOB', 0, 0, 0, 0, 'ENABLED', NOW(), NOW()),
('TICKET', 'START_REPAIR', '开始处理', 'MANUAL', 0, 0, 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'AUTO_START_REPAIR', '自动进入处理', 'JOB', 0, 0, 0, 0, 'ENABLED', NOW(), NOW()),
('TICKET', 'MARK_WAIT_PARTS', '标记等待配件', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'PARTS_ARRIVED', '配件到齐继续处理', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'SUBMIT_REPAIR_DONE', '提交处理完成', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'PREPARE_OUTBOUND', '出库准备完成', 'MANUAL', 0, 0, 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'SUBMIT_OUTBOUND', '提交出库', 'MANUAL', 0, 1, 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'SYNC_LOGISTICS', '物流状态回写', 'API', 0, 0, 0, 0, 'ENABLED', NOW(), NOW()),
('TICKET', 'CONFIRM_STORE_RECEIVE', '确认门店收货', 'MANUAL', 0, 0, 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'MARK_STORE_READY_PICKUP', '标记门店可取', 'MANUAL', 0, 0, 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'CONFIRM_CUSTOMER_PICKUP', '确认客户取件', 'MANUAL', 0, 0, 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'AUTO_COMPLETE', '自动服务完成', 'JOB', 0, 0, 0, 0, 'ENABLED', NOW(), NOW()),
('TICKET', 'CANCEL_TICKET', '取消工单', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('INVENTORY_REQUEST', 'SUBMIT_PROCESS', '开始处理申请', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('INVENTORY_REQUEST', 'COMPLETE_REQUEST', '完成申请处理', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('INVENTORY_REQUEST', 'CLOSE_REQUEST', '关闭申请', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('PART_REQUEST', 'SUBMIT_OUTBOUND', '提交出库', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('PART_REQUEST', 'COMPLETE_REQUEST', '完成申请', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('PART_REQUEST', 'CLOSE_REQUEST', '关闭申请', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'START_PROCESS', '开始处理事项', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'COMPLETE_ITEM', '完成事项', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'CLOSE_ITEM', '关闭事项', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'CUSTOMER_CONFIRM_PASS', '客户确认通过', 'API', 0, 0, 0, 0, 'ENABLED', NOW(), NOW()),
('CONSULTATION', 'CUSTOMER_CONFIRM_REJECT', '客户确认拒绝', 'API', 0, 0, 0, 0, 'ENABLED', NOW(), NOW()),
('SURVEY', 'INVALIDATE_SURVEY', '问卷失效', 'MANUAL', 1, 0, 1, 1, 'ENABLED', NOW(), NOW()),
('SURVEY', 'EXPIRE_SURVEY', '问卷过期', 'JOB', 0, 0, 0, 0, 'ENABLED', NOW(), NOW());
