INSERT INTO wf_auto_rule (
  biz_type, rule_code, from_status_code, action_code, trigger_mode,
  trigger_expr, calendar_type, is_holiday_excluded, retryable, status,
  created_at, updated_at
) VALUES
('TICKET', 'RULE_FREE_AUTO_START_REPAIR', 'JUDGED_FREE', 'AUTO_START_REPAIR', 'TIME', '+D3', 'WORKDAY', 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'RULE_PAID_AUTO_START_REPAIR', 'PAYMENT_COMPLETED', 'AUTO_START_REPAIR', 'TIME', '+D3', 'WORKDAY', 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'RULE_MARK_PAYMENT_OVERDUE', 'WAIT_PAYMENT', 'MARK_PAYMENT_OVERDUE', 'TIME', '+D29', 'NATURAL_DAY', 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'RULE_PAY_TIMEOUT_CLOSE', 'PAYMENT_OVERDUE', 'PAY_TIMEOUT_CLOSE', 'TIME', '+D1', 'NATURAL_DAY', 0, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'RULE_SIGNED_AUTO_COMPLETE', 'CUSTOMER_SIGNED', 'AUTO_COMPLETE', 'TIME', '+D1', 'WORKDAY', 1, 1, 'ENABLED', NOW(), NOW()),
('TICKET', 'RULE_PICKED_AUTO_COMPLETE', 'CUSTOMER_PICKED', 'AUTO_COMPLETE', 'TIME', '+D1', 'WORKDAY', 1, 1, 'ENABLED', NOW(), NOW()),
('SURVEY', 'RULE_SURVEY_AUTO_EXPIRE', 'PENDING', 'EXPIRE_SURVEY', 'TIME', 'deadline_at', 'NATURAL_DAY', 0, 1, 'ENABLED', NOW(), NOW());
